name: Docker Image Deployment to Azure Web App

on:
  push:
    branches: [ "Transform_1" ]
  pull_request:
    branches: [ "Transform_1" ]
env:
  DOCKER_IMAGE_NAME: 'transform_1_traintimes'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal ./TrainTimesTests/bin/Release/net7.0/TrainTimesTests.dll
   
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
      
    - name: Docker Login
      run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'
    - name: Tag the Docker image
      run: docker tag '${{env.DOCKER_IMAGE_NAME}}':latest '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':latest
    - name: Push the Docker image
      run: docker push '${{secrets.DOCKER_LOGIN}}'/'${{env.DOCKER_IMAGE_NAME}}':latest
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'HW-TrainTimes'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B848B570BFD34970A24EA0E5DF5E09B7 }}
        images: '${{secrets.DOCKER_LOGIN}}/${{env.DOCKER_IMAGE_NAME}}:latest'
